on:
  issues:
    types:
      ['labeled', 'unlabeled']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: |
      (github.event.label.name == '対応中') || (github.event.label.name == '依頼中')
    name: A job to say hello
    steps:
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Comment
        run: |
          echo "test comments"
      - name: POST Comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          URL: ${{ github.event.issue.comments_url }}
        run: |
          comments="$GITHUB_API_URL"
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"body\": \"$(cat comment)\"}" ${URL}
