on:
  issues:
    types:
      ['labeled', 'unlabeled']

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    if: |
      (github.event.label.name == '対応中') || (github.event.label.name == '依頼中')
    name: Recording label's add or remove time
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Tokyo
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current date-time
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"
      - name: POST Comment
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          URL: ${{ github.event.issue.comments_url }}
          LABEL_NAME: ${{ github.event.label.name }}
        run: |
          comments="$GITHUB_API_URL"
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d "{\"body\": \"${{ steps.date.outputs.date }}\n$LABEL_NAME\"}" ${URL}
